// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDdw7PCxQ0W0lHRUt5wMO_rH9QGWEGBq4',
    appId: '1:700615102727:web:65753982db7f5b7272b5a2',
    messagingSenderId: '700615102727',
    projectId: 'login-219ea',
    authDomain: 'login-219ea.firebaseapp.com',
    storageBucket: 'login-219ea.appspot.com',
    measurementId: 'G-V5FWF8S896',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjgpqVRXRm8LChPxxRj17lQNRU6-CeCWM',
    appId: '1:700615102727:android:cf7a0617c533b8cd72b5a2',
    messagingSenderId: '700615102727',
    projectId: 'login-219ea',
    storageBucket: 'login-219ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI6o0D82zqjiulXZKiKmMqJdo1YCHBWxk',
    appId: '1:700615102727:ios:fb04d003c139d42e72b5a2',
    messagingSenderId: '700615102727',
    projectId: 'login-219ea',
    storageBucket: 'login-219ea.appspot.com',
    iosBundleId: 'com.example.loginGoogle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCI6o0D82zqjiulXZKiKmMqJdo1YCHBWxk',
    appId: '1:700615102727:ios:568795a7f3565cd172b5a2',
    messagingSenderId: '700615102727',
    projectId: 'login-219ea',
    storageBucket: 'login-219ea.appspot.com',
    iosBundleId: 'com.example.loginGoogle.RunnerTests',
  );
}
